"""Execute worked notebooks and preserve reproducible text/figure outputs."""
from pathlib import Path
import json,io,contextlib,os,time,sys
import nbformat
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[1]
os.chdir(ROOT)
paths=[ROOT/p for p in sys.argv[1:]] if len(sys.argv)>1 else sorted(ROOT.glob('day-0[2-5]*/*worked.ipynb'))
for p in paths:
 print('RUN',p.relative_to(ROOT),flush=True)
 nb=nbformat.read(p,as_version=4);nbformat.validate(nb)
 ns={'__name__':'__main__'};outputs=[];counter=0
 figures=p.parent/'figures';figures.mkdir(exist_ok=True)
 for i,cell in enumerate(nb.cells):
  if cell.cell_type!='code':continue
  buf=io.StringIO();counter+=1
  with contextlib.redirect_stdout(buf),contextlib.redirect_stderr(buf):exec(compile(cell.source,str(p), 'exec'),ns)
  out=buf.getvalue();outputs.append(out)
  cell.execution_count=counter;cell.outputs=[]
  if out:cell.outputs.append(nbformat.v4.new_output('stream',name='stdout',text=out))
  for num in plt.get_fignums():
   fig=plt.figure(num);name=f'{p.stem}-cell-{counter}-figure-{num}.svg';fig.savefig(figures/name,bbox_inches='tight')
  plt.close('all')
 # Keep output values in a separate executed copy so learners can read results offline.
 nbformat.write(nb,p.with_name(p.stem+'_executed.ipynb'))
 checks=[]
 if p.parent.name.startswith('day-02'):
  assert len(ns['X_test'])==100 and not set(ns['train_ids'])&set(ns['test_ids'])
  assert len(ns['pred'])==100;checks=['Disjoint 300/100 split; 100 classification predictions.']
 if p.parent.name.startswith('day-03'):
  assert ns['train'].index.max()<ns['test'].index.min();assert len(ns['pred'])==28
  assert ns['fit'].mle_retvals.get('converged');checks=['Chronological split; 28 forecasts; ARIMA optimiser converged.']
 if p.parent.name.startswith('day-04'):
  assert (ns['post_a'],ns['post_b'])==(10,110)
  assert abs(ns['chains'].mean()-10/120)<.005;checks=['Exact Beta(10,110); MCMC mean within 0.005 of exact mean.']
 if p.name=='spark_worked.ipynb':checks=['SQL/DataFrame agreement and model baseline assertions passed.']
 if p.parent.name.startswith('day-05') and p.name=='worked.ipynb':
  assert ns['np'].isfinite(ns['generated']).all();checks=['Map/reduce totals asserted; finite adversarial generator samples.']
 report='# Executed results: '+p.name+'\n\nGenerated by scripts/validate_days.py. Code cells executed sequentially in a fresh namespace; chart sources saved under figures/. Values are synthetic demonstrations.\n\nChecks: '+' '.join(checks)+'\n\n'
 for i,out in enumerate(outputs,1):report+=f'## Code cell {i}\n\n```text\n{out}\n```\n\n'
 (p.parent/(p.stem+'_RESULTS.md')).write_text(report)
 print('PASS',p.relative_to(ROOT),flush=True)
